version: '2'

services: 
  drupal:
    image: drupal
    ports: 
      - '8080:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/theme

  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=secrets
    
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

