sudo: required
services:
  - docker

before_install:
  - docker build -t utumno86/docker-react -f DockerKubernetesCourse/frontend/Dockerfile.dev DockerKubernetesCourse/frontend/

script:
  - docker run utumno86/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-821037481133"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  zip_file: DockerKubernetesCourse/frontend/