apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: fibonacci-sequence-us-tls
spec:
  secretName: fibonacci-sequence-us
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fibonaccisequence.us
  dnsNames:
    - fibonaccisequence.us
    - www.fibonaccisequence.us
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fibonaccisequence.us
          - www.fibonaccisequence.us
