apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-vo2.api.letsencrypt.org/directory
    email: 'utumno86@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
